_target_: "ranking_lib.dataset.datamodule.BaseDataModule"
_recursive_: False

defaults:
  - preprocessor/base
  - train_dataset/base
  - valid_dataset/base

train_dataloader:
  _target_: "torch.utils.data.DataLoader"
  batch_size: 96
  num_workers: 10

valid_dataloader:
  _target_: "torch.utils.data.DataLoader"
  batch_size: 256
  num_workers: ${datamodule.train_dataloader.num_workers}